/* autogenerated by Processing revision 1293 on 2024-10-07 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class EARTH_QUEST extends PApplet {

String estadoJuego = "Inicio"; //Estado actual del juego

PImage fondoInicio, fondoNivel1, fondoNivel2, fondoSelect, personajeFijo;
PImage[] personajes;
int personajeActual = 0;
int fondoNivel1X = 0;
int personajeFijoX = -100; //patinadora
int personajeFijoY = 600;
int velocidadFondo = 3;
int personajeMovilX; //personaje que se mueve con el fondo
int velocidadPersonaje = 3;
int[] otrosPersonajesX = {600, 1000, 1500};

public void setup() {
  /* size commented out by preprocessor */;
  fondoInicio = loadImage("mainmenu6.jpg"); 
  fondoSelect = loadImage("select4.png");
  fondoNivel1 = loadImage("atmosphere5.png");
  fondoNivel2 = loadImage("fondoprueba.jpg");
  personajeFijo = loadImage("personajeprin4.png");
  personajes = new PImage[14];
  personajes[0] = loadImage("personaje1.png");
  personajes[1] = loadImage("personaje2.png");
  personajes[2] = loadImage("personaje3.png");

  /* noSmooth commented out by preprocessor */;
  /* size commented out by preprocessor */;
}

public void draw() {
  if (estadoJuego.equals("Inicio")) {
    pantallaInicio(); //Mostrar pantalla inicio
  } else if (estadoJuego.equals("Select")) {
    Select();
  } else if (estadoJuego.equals("Atmosphere")) {
    Atmosphere(); //Mostrar nivel atmosphere
  } else if (estadoJuego.equals("Nivel2")) {
    Biosphere();
  }
}
public void pantallaInicio() {
  image(fondoInicio, 100, 0);
  rect(750, 460, 250, 100);
  fill(255, 0);
  noStroke();
}
public void Select() {
  image(fondoSelect, 0, 0);
  rect(80, 115, 370, 340);
  fill(255, 0);
  noStroke();  
}
public void Atmosphere() {
  image(fondoNivel1, fondoNivel1X, 0, width, height);
  image(fondoNivel1, fondoNivel1X + width, 0, width, height);
  if (fondoNivel1X <= -width) { //el bucle del fondo
    fondoNivel1X = 0;
    personajeActual = (personajeActual + 1) % personajes.length; //el personaje cambia cuando empieza otro bucle
  }
  image(personajes[personajeActual], personajeMovilX + 500, 300);
  image(personajeFijo, personajeFijoX, personajeFijoY - 200);

  //rect(200, 500, 150, 100);
  //fill(255, 255);
  if (keyPressed && keyCode == RIGHT) {
    fondoNivel1X -= velocidadFondo; //se mueve el fondo
    personajeMovilX -= velocidadPersonaje; // se mueve el personaje
  }
}
public void Biosphere() {
  image(fondoNivel2, 0, 0);
  rect(200, 500, 150, 100);
  fill(255, 255);
}
public void mousePressed() {
  if (estadoJuego.equals("Inicio")) {
    if (mouseX > 750 && mouseX < 750 + 250 && mouseY > 460 && mouseY < 460 + 100) {
      estadoJuego = "Select"; // Cambiar al nivel 1 60, 380, 400, 50)
    }
  }
  if (estadoJuego.equals("Select")) {
    if (mouseX > 80 && mouseX < 80 + 370 && mouseY > 115 && mouseY < 115 + 340) {
      estadoJuego = "Atmosphere";
    }
  }
}


  public void settings() { fullScreen();
noSmooth(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "EARTH_QUEST" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
